# Generated by Django 3.0.6 on 2020-05-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('ref_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('page_link', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ref_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('page_link', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('organizers', models.ManyToManyField(related_name='events', to='cvonline.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='cvonline.Event')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendee_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clubs', models.ManyToManyField(related_name='members', to='cvonline.Club')),
            ],
        ),
    ]
