# Generated by Django 3.0.6 on 2020-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0002_auto_20200512_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_link',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
