# Generated by Django 3.0.6 on 2020-05-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0003_auto_20200512_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user_from',
        ),
        migrations.AddField(
            model_name='donation',
            name='attn_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='cvonline.Attendee'),
        ),
    ]
