# Generated by Django 3.0.6 on 2020-05-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0005_auto_20200512_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('cumulative', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendee_owner', to='cvonline.Balance'),
        ),
        migrations.AddField(
            model_name='event',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_owner', to='cvonline.Balance'),
        ),
    ]
