# Generated by Django 3.0.6 on 2020-05-12 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0006_auto_20200512_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
