# Generated by Django 3.0.6 on 2020-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0007_auto_20200512_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
