# Generated by Django 3.0.6 on 2020-05-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvonline', '0008_club_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club_owner', to='cvonline.Balance'),
        ),
    ]
