# Generated by Django 3.0.6 on 2020-05-13 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squarepay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpayment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
